# numpy

### 1) numpy vs arrays

#### -python list serve the process of array but are slow to process
#### -numpy arrays are 50x faster than the python lists 
#### -NumPy arrays can also be two-dimensional, three-dimensional, or up to n-dimensional.

## 2) create numpy

In [1]:
# importing lib
import numpy as np

#### Create a NumPy ndarray Object

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
# printing the array
print(arr)

[1 2 3 4 5]


In [5]:
# checking the type of arr
type(arr)

numpy.ndarray

![](https://i.imgur.com/mg8O3kd.png)

#### 0-d Array

In [6]:
arr = np.array(10)

In [7]:
print(arr)

10


#### # 1D array (vector)

In [20]:
arr1 = np.array([1,2,3,4,5])


In [21]:
print(arr1)

[1 2 3 4 5]


In [22]:
arr1.shape

(5,)

##### 2D array (matrix)

In [24]:
arr2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [25]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr2.shape

(3, 3)

#### 3-d Array

In [38]:
 arr3 = np.array([[[1,2,3],
                  [4,5,6]],
                 [[1,2,3],
                  [4,5,6]]])

In [39]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [40]:
arr3.shape

(2, 2, 3)

In [41]:
arr = np.array([[[1,2,3,4],
                 [2,3,4]],
                [[2,3,4],
                 [2,5,6]]])

In [43]:
arr.shape

(2, 2)

In [44]:
arr

array([[list([1, 2, 3, 4]), list([2, 3, 4])],
       [list([2, 3, 4]), list([2, 5, 6])]], dtype=object)

### Datatypes 
#### float8 does not exist. only int8,int16,int64,float16,float64

In [45]:
arr1 = np.array([1,2,3])

In [46]:
arr1.dtype

dtype('int32')

In [47]:
arr2 = np.array([2,4,5.0])

In [48]:
arr2.dtype

dtype('float64')

# 3)Operations

In [8]:
arr1 = np.array([2,4,6])
arr2 = np.array([2,4,6])

# * performs element wise multiplication
arr1 * arr2



array([ 4, 16, 36])

In [10]:
# performs element wise multiplication and adds them 
np.dot(arr1,arr2)

56

#### We can use the np.matmul function or the @ operator to perform matrix multiplication.



<img src="https://i.imgur.com/LJ2WKSI.png" width="240">

In [57]:
weights = np.array([0.3, 0.4, 0.5])

In [58]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [59]:
np.matmul(climate_data, weights)

array([ 70.2,  94.5, 108.7,  66.3,  94.1])

In [53]:
climate_data @ weights

array([ 70.2,  94.5, 108.7,  66.3,  94.1])

## Working with CSV data files

Numpy also provides helper functions reading from & writing to files. Let's download a file `climate.txt`, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:

```
temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```

In [7]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x2dfb97fde10>)

#### To read this file into a numpy array, we can use the genfromtxt function.

In [8]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [9]:
print(climate_data) 

[[25. 76. 99.]
 [39. 65. 70.]
 [59. 45. 77.]
 ...
 [99. 62. 58.]
 [70. 71. 91.]
 [92. 39. 76.]]


In [10]:
climate_data.shape

(10000, 3)

In [11]:
# declaring the weights
weights = np.array([0.1, 0.2, 0.3])

In [12]:
weights

array([0.1, 0.2, 0.3])

In [13]:
# using matmul function on climate_data and weights (matmul = matrix multiplication)
yields = np.matmul(climate_data, weights)

In [14]:
yields

array([47.4, 37.9, 38. , ..., 39.7, 48.5, 39.8])

In [15]:
# the shape of yields (currently 1-d)
yields.shape

(10000,)

In [16]:
yields.reshape(10000,1)

array([[47.4],
       [37.9],
       [38. ],
       ...,
       [39.7],
       [48.5],
       [39.8]])

Let's add the `yields` to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.

In [17]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis=1 )

In [18]:
climate_results

array([[25. , 76. , 99. , 47.4],
       [39. , 65. , 70. , 37.9],
       [59. , 45. , 77. , 38. ],
       ...,
       [99. , 62. , 58. , 39.7],
       [70. , 71. , 91. , 48.5],
       [92. , 39. , 76. , 39.8]])

In [19]:
np.savetxt('climate_results.txt',
            climate_results,
            fmt='%.2f',
            delimiter=',',
            header='temperature,rainfall,humidity,yeild_apples',
            comments='')

There are a couple of subtleties here:

* Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`. The `axis` argument specifies the dimension for concatenation.

*  The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function to change the shape of `yields` from `(10000,)` to `(10000,1)`.
<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

In [20]:
arr = np.array([1,2,3,4,5,6])

arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Arithmetic Operations , broadcasting and comparison

In [24]:
arr2 = np.array([[2,3,5],
                [1,5,3],
                [7,5,3]])


In [26]:
arr3 = np.array([[12,13,15],
                 [11,15,13],
                 [17,15,13]])

In [28]:
# Adding a scalar
arr2 + 3

array([[ 5,  6,  8],
       [ 4,  8,  6],
       [10,  8,  6]])

In [30]:
# Element wise subtraction 
arr3 - arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [31]:
# dividing by scalar
arr3 / 2


array([[6. , 6.5, 7.5],
       [5.5, 7.5, 6.5],
       [8.5, 7.5, 6.5]])

In [33]:
# element wise multiplication
arr2 * arr3

array([[ 24,  39,  75],
       [ 11,  75,  39],
       [119,  75,  39]])

In [35]:
# modulus with scalar
arr2 % 2

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

### Array Broadcasting


In [38]:
arr2 = np.array([[2,4,6],
                 [3,2,3],
                 [3,2,6]])

In [39]:
arr2.shape

(3, 3)

In [40]:
arr4 = np.array([1,1,1])

In [41]:
arr4.shape

(3,)

In [42]:
arr2 + arr4

array([[3, 5, 7],
       [4, 3, 4],
       [4, 3, 7]])

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated three times to match the shape `(3, 4)` of `arr2`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [44]:
arr1 = np.array([2,4])

In [45]:
arr1.shape

(2,)

In [46]:
arr1

array([2, 4])

In [47]:
arr3

array([[12, 13, 15],
       [11, 15, 13],
       [17, 15, 13]])

In [49]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

### Array Comparison

In [51]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[1,5,3],
                [4,3,6]])

In [52]:
arr1 == arr2

array([[ True, False,  True],
       [ True, False,  True]])

In [53]:
arr1 != arr2

array([[False,  True, False],
       [False,  True, False]])

In [56]:
arr1 > arr2

array([[False, False, False],
       [False,  True, False]])

## Array Indexing and Slicing

In [57]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [59]:
arr3.shape

(3, 2, 4)

In [60]:
# single element
arr3[1, 1, 2]

36.0

In [63]:
# subarray using ranges
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [65]:
# subarray using mixed ranges and indices
arr3[1:, 1, 3]

array([18., 43.])

In [66]:
arr3[1:, 1,:3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [67]:
arr3[:2,1,]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

## Other ways of creating Numpy arrays

In [68]:
# all zeroes
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
# all ones
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
# random vector
np.random.rand(5)

array([0.86792839, 0.34496659, 0.64175225, 0.10664717, 0.76098267])

In [76]:
# random matrix
np.random.randn(3,3)

array([[ 1.68928905, -0.14678055, -0.78361676],
       [ 1.30015776, -1.18339108,  0.11597054],
       [-0.04756902,  0.76738114, -0.03089114]])

In [77]:
# fixed value
np.full([2,3],30)

array([[30, 30, 30],
       [30, 30, 30]])

In [80]:
# range with start , stop and step
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
#  Equally spaced numbers in a range
np.linspace(3,30,9)

array([ 3.   ,  6.375,  9.75 , 13.125, 16.5  , 19.875, 23.25 , 26.625,
       30.   ])

# 4)Delete